### ISSUE TITLE
Feat/Hashers: Hash160

### ISSUE THREAD

**Issue by StringNick** [zig-bitcoin/bitcoin-primitives#4]
We need implement hash160, ripemd160 already implemented, only what u need to create zig style hashing struct, call ripemd and sha256  + tests.
Test u can took from rust [implementation](https://github.com/rust-bitcoin/rust-bitcoin/blob/0123f2894c66419f1ad561e9e7d98af66c4db9ab/hashes/src/hash160.rs)

**Comment by RedVelvetZip** [comment]
howdy, can I take this ticket?
